---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
prerelease: true
include-pre-releases: true
categories:
  - title: 💣 Breaking Changes
    labels:
      - breaking change
  - title: 🔔 Deprecation Warnings
    labels:
      - deprecation
  - title: 🚀 Features
    labels:
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🧪 Tests
    labels:
      - tests
  - title: 🔨 Maintenance
    labels:
      - maintenance
  - title: 👷 CI/CD
    labels:
      - ci
  - title: ⬆️ Dependencies
    collapse-after: 15
    labels:
      - dependencies
  - title: 📝 Documentation
    labels:
      - documentation
  - title: Other Changes
    labels:
      - "*"
exclude-labels:
  - skip changelog
version-resolver:
  minor:
    labels:
      - breaking change
      - deprecation
  patch:
    labels:
      - enhancement
      - bug
      - tests
      - documentation
      - ci
      - maintenance
      - dependencies
  default: patch
autolabeler:
  - label: breaking change
    body:
      - "/breaking/i"
  - label: deprecation
    body:
      - "/deprecate/i"
  - label: enhancement
    title:
      - "/^[^:]*(feat|feature|perf)(\\([^)]*\\))?:/i"
  - label: bug
    title:
      - "/^[^:]*(bug)(\\([^)]*\\))?:/i"
  - label: tests
    title:
      - "/^[^:]*(test|tests)(\\([^)]*\\))?:/i"
  - label: documentation
    title:
      - "/^[^:]*(docs|documentation)(\\([^)]*\\))?:/i"
  - label: ci
    title:
      - "/^[^:]*(ci|build)(\\([^)]*\\))?:/i"
  - label: maintenance
    title:
      - "/^[^:]*(chore|refactor|style|revert)(\\([^)]*\\))?:/i"
  - label: dependencies
    title:
      - "/.+\\sto\\sv.+"
#replacers:
#  - search: "/[^:]*(\\w+)(\\(\\w+\\))?!?: /g"
#    replace: ""
template: |
  ## What's new in Listmonk's Ansible role $RESOLVED_VERSION!

  $CHANGES

  ## Install & Upgrade

  - To install the Ansible Listmonk role on a fresh environment, run `ansible-galaxy install idNoRD.listmonk`.
  - To upgrade the Ansible Listmonk role to the latest release, run `ansible-galaxy install -f idNoRD.listmonk`.
  - To install or upgrade to this specific Ansible Listmonk role release ($RESOLVED_VERSION), run `ansible-galaxy install -f idNoRD.listmonk,v$RESOLVED_VERSION`.

  ## Resources

  - Ansible Galaxy repository -- [galaxy.ansible.com/idNoRD/listmonk](https://galaxy.ansible.com/idNoRD/listmonk/).
