---
- name: "Create config directory: {{ listmonk.config_dir }}"
  ansible.builtin.file:
    path: "{{ listmonk.config_dir }}"
    state: directory
    owner: "{{ listmonk.service_user }}"
    group: "{{ listmonk.service_group }}"
    mode: '0400'
  become: true

- name: "Copy the configuration file to the config directory"
  template:
    src: config.toml.j2
    dest: "{{ listmonk.config_dir }}/config.toml"
    owner: "{{ listmonk.service_user }}"
    group: "{{ listmonk.service_group }}"
    mode: '0400'
  become: true
  notify: restart listmonk
