---
- name: Ensure required package firewalld are installed
  ansible.builtin.include_tasks: fastpackages.yml
  vars:
    packages_list:
      - firewalld

- name: Enable and start the firewalld service
  become: true
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: "Configure firewall for {{ listmonk.service_name }} http port"
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ listmonk_http_port }}/tcp"
  when: listmonk_http_enabled | bool

- name: "Configure firewall for {{ listmonk.service_name }} ports"
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ listmonk_https_port }}/tcp"
  when: not listmonk_http_enabled | bool

