---
- name: "Wait until {{ listmonk.service_name }} becomes active {{ listmonk.health_url }}"
  block:
    - name: "Check if {{ listmonk.service_name }} is healthy at {{ listmonk.health_url }}"
      ansible.builtin.uri:
        url: "{{ listmonk.health_url }}"
      register: listmonk_status
      until: listmonk_status.status == 200
      retries: "{{ listmonk_restart_health_check_retries }}"
      delay: "{{ listmonk_restart_health_check_delay }}"
  rescue:
    - name: Get full systemctl status output
      ansible.builtin.command: "systemctl status {{ listmonk.service_name }}"
      register: listmonk_systemctl_output
      changed_when: false
      failed_when: false
    - name: Show Listmonk failure status
      ansible.builtin.debug:
        msg: "{{ listmonk_systemctl_output.stdout.splitlines() }}"
    - name: Stop the play if failed to become healthy
      ansible.builtin.fail:
        msg: "Listmonk failed to become healthy."