---
- name: "Start {{ listmonk.service_name }} service"
  ansible.builtin.systemd:
    name: listmonk
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: "Wait until {{ listmonk.service_name }} becomes active {{ listmonk.health_url }}"
  ansible.builtin.uri:
    url: "{{ listmonk.health_url }}"
  register: listmonk_status
  until: listmonk_status.status == 200
  retries: "{{ listmonk_restart_health_check_retries }}"
  delay: "{{ listmonk_restart_health_check_delay }}"
  when: listmonk_restart_health_check