---
- name: "Start {{ listmonk.service_name }} service"
  ansible.builtin.systemd:
    name: "{{ listmonk.service_name }}"
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Check for healthcheck
  ansible.builtin.include_tasks: healthcheck.yml
  when: listmonk_restart_health_check
