---
- name: "Configure sysconfig file for {{ listmonk.service_name }} service"
  become: true
  ansible.builtin.template:
    src: listmonk-sysconfig.j2
    dest: "{{ listmonk_sysconf_file }}"
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart listmonk

- name: "Configure systemd unit file for listmonk service"
  ansible.builtin.template:
    src: listmonk.service.j2
    dest: /etc/systemd/system/listmonk.service
    owner: root
    group: root
    mode: '0644'
  become: true
  register: systemdunit
  notify:
    - restart listmonk
