---
name: Fedora 41

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches: []

jobs:
  ansible-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3
      - name: Test Galaxy role
        run: >
          CONT_ID=$(podman run --rm -v ${{ github.workspace }}:/repo -v /sys/fs/cgroup:/sys/fs/cgroup:ro
          --tmpfs /tmp --tmpfs /run --privileged --detach bviktor/ansible-systemd-fedora:41) &&
          podman exec ${CONT_ID} /bin/bash -c
          "if [ -f requirements.yml ]; then ansible-galaxy role install --force -r requirements.yml -p ..; fi &&
          ./install-postgres-for-cicd.sh &&
          ANSIBLE_ROLES_PATH=.. ANSIBLE_FORCE_COLOR=true ansible-playbook tests/test-running-in-cicd.yml" &&
          podman stop ${CONT_ID}
