---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches: []

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v4
      - name: Lint sources
        run: >
          podman run --rm -v ${{ github.workspace }}:/repo bviktor/ansible-systemd-lint:latest /bin/bash -c
          "git config --global --add safe.directory /repo &&
          yamllint --strict . &&
          ansible-lint --strict"
